
package es.udc.ws.jaxwstutorial.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IncorrectTickerSymbolException", targetNamespace = "http://ws.udc.es/stockquote")
public class IncorrectTickerSymbolException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IncorrectTickerSymbolExceptionInfo faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IncorrectTickerSymbolException(String message, IncorrectTickerSymbolExceptionInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IncorrectTickerSymbolException(String message, IncorrectTickerSymbolExceptionInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.udc.ws.jaxwstutorial.wsdl.IncorrectTickerSymbolExceptionInfo
     */
    public IncorrectTickerSymbolExceptionInfo getFaultInfo() {
        return faultInfo;
    }

}
