
package es.udc.ws.jaxwstutorial.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StockQuoteProvider", targetNamespace = "http://ws.udc.es/stockquote")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StockQuoteProvider {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<es.udc.ws.jaxwstutorial.wsdl.TradePrice>
     * @throws IncorrectTickerSymbolException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastTradePrices", targetNamespace = "http://ws.udc.es/stockquote", className = "es.udc.ws.jaxwstutorial.wsdl.GetLastTradePrices")
    @ResponseWrapper(localName = "getLastTradePricesResponse", targetNamespace = "http://ws.udc.es/stockquote", className = "es.udc.ws.jaxwstutorial.wsdl.GetLastTradePricesResponse")
    @Action(input = "http://ws.udc.es/stockquote/StockQuoteProvider/getLastTradePricesRequest", output = "http://ws.udc.es/stockquote/StockQuoteProvider/getLastTradePricesResponse", fault = {
        @FaultAction(className = IncorrectTickerSymbolException.class, value = "http://ws.udc.es/stockquote/StockQuoteProvider/getLastTradePrices/Fault/IncorrectTickerSymbolException")
    })
    public List<TradePrice> getLastTradePrices(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0)
        throws IncorrectTickerSymbolException
    ;

}
