
package es.udc.ws.jaxwstutorial.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StockQuoteProviderService", targetNamespace = "http://ws.udc.es/stockquote", wsdlLocation = "file:/D:/udc/svn/ws-javaexamples/ws-jaxwstutorial/ws-jaxwstutorial-service/target/generated-sources/wsdl/StockQuoteProviderService.wsdl")
public class StockQuoteProviderService
    extends Service
{

    private final static URL STOCKQUOTEPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException STOCKQUOTEPROVIDERSERVICE_EXCEPTION;
    private final static QName STOCKQUOTEPROVIDERSERVICE_QNAME = new QName("http://ws.udc.es/stockquote", "StockQuoteProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/udc/svn/ws-javaexamples/ws-jaxwstutorial/ws-jaxwstutorial-service/target/generated-sources/wsdl/StockQuoteProviderService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STOCKQUOTEPROVIDERSERVICE_WSDL_LOCATION = url;
        STOCKQUOTEPROVIDERSERVICE_EXCEPTION = e;
    }

    public StockQuoteProviderService() {
        super(__getWsdlLocation(), STOCKQUOTEPROVIDERSERVICE_QNAME);
    }

    public StockQuoteProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STOCKQUOTEPROVIDERSERVICE_QNAME, features);
    }

    public StockQuoteProviderService(URL wsdlLocation) {
        super(wsdlLocation, STOCKQUOTEPROVIDERSERVICE_QNAME);
    }

    public StockQuoteProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STOCKQUOTEPROVIDERSERVICE_QNAME, features);
    }

    public StockQuoteProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockQuoteProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StockQuoteProvider
     */
    @WebEndpoint(name = "StockQuoteProviderPort")
    public StockQuoteProvider getStockQuoteProviderPort() {
        return super.getPort(new QName("http://ws.udc.es/stockquote", "StockQuoteProviderPort"), StockQuoteProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockQuoteProvider
     */
    @WebEndpoint(name = "StockQuoteProviderPort")
    public StockQuoteProvider getStockQuoteProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.udc.es/stockquote", "StockQuoteProviderPort"), StockQuoteProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STOCKQUOTEPROVIDERSERVICE_EXCEPTION!= null) {
            throw STOCKQUOTEPROVIDERSERVICE_EXCEPTION;
        }
        return STOCKQUOTEPROVIDERSERVICE_WSDL_LOCATION;
    }

}
